# Logging
debug: false
trace: false
logging:
  file.path: "./logs/"
  level:
    root: "INFO"
    org.springframework.web.servlet.DispatcherServlet: "DEBUG"

# Spring
spring:
  profiles:
    active: "local,dev,prom"
  output:
    ansi:
      enabled: "detect"
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"

# Custom application properties
application:
  show:
    context: "true"

